export const products = {
    category: [
      {
        category: "T-Shirt",
        data: [
          {
            name: "t-shirt 1",
            price: 9874,
            gender: "male",
            image: require("./../images/ts1.jpg"),
          },
          {
            name: "t-shirt 2",
            price: 3214,
            gender: "male",
            image: require("./../images/ts2.jpg"),
          },
          {
            name: "t-shirt 3",
            price: 6547,
            gender: "male",
            image: require("./../images/ts3.jpg"),
          },
          {
            name: "t-shirt 4",
            price: 9874,
            gender: "male",
            image: require("./../images/ts4.jpg"),
          },
          {
            name: "t-shirt 5",
            price: 6541,
            gender: "male",
            image: require("./../images/ts5.jpg"),
          },
          {
            name: "t-shirt 6",
            price: 6321,
            gender: "male",
            image: require("./../images/ts6.jpg"),
          },
          {
            name: "t-shirt 7",
            price: 9874,
            gender: "male",
            image: require("./../images/ts7.jpg"),
          },
          {
            name: "t-shirt 8",
            price: 9632,
            gender: "male",
            image: require("./../images/ts8.jpg"),
          },
          {
            name: "t-shirt 9",
            price: 1581,
            gender: "male",
            image: require("./../images/ts9.jpg"),
          },
          {
            name: "t-shirt 10",
            price: 456,
            gender: "male",
            image: require("./../images/ts10.jpg"),
          },
        ],
      },
      {
        category: "Jeans",
        data: [
          {
            name: "Jeans 1",
            price: 299,
            gender: "male",
            image: require("./../images/j1.jpg"),
          },
          {
            name: "Jeans 2",
            price: 299,
            gender: "male",
            image: require("./../images/j2.jpg"),
          },
          {
            name: "Jeans 3",
            price: 299,
            gender: "male",
            image: require("./../images/j3.jpg"),
          },
          {
            name: "Jeans 4",
            price: 299,
            gender: "male",
            image: require("./../images/j4.jpg"),
          },
          {
            name: "Jeans 5",
            price: 299,
            gender: "male",
            image: require("./../images/j5.jpg"),
          },
          {
            name: "Jeans 6",
            price: 299,
            gender: "male",
            image: require("./../images/j6.jpg"),
          },
          {
            name: "Jeans 7",
            price: 299,
            gender: "male",
            image: require("./../images/j7.jpg"),
          },
          {
            name: "Jeans 8",
            price: 299,
            gender: "male",
            image: require("./../images/j8.jpg"),
          },
          {
            name: "Jeans 9",
            price: 299,
            gender: "male",
            image: require("./../images/j9.jpg"),
          },
          {
            name: "Jeans 10",
            price: 299,
            gender: "male",
            image: require("./../images/j10.jpg"),
          },
        ],
      },
      {
        category: "Shirts",
        data: [
          {
            name: "Shirt 1",
            price: 299,
            gender: "male",
            image: require("./../images/st1.jpg"),
          },
          {
            name: "Shirt 2",
            price: 299,
            gender: "male",
            image: require("./../images/st2.jpg"),
          },
          {
            name: "Shirt 3",
            price: 299,
            gender: "male",
            image: require("./../images/st3.jpg"),
          },
          {
            name: "Shirt 4",
            price: 299,
            gender: "male",
            image: require("./../images/st4.jpg"),
          },
          {
            name: "Shirt 5",
            price: 299,
            gender: "male",
            image: require("./../images/st5.jpg"),
          },
          {
            name: "Shirt 6",
            price: 299,
            gender: "male",
            image: require("./../images/st6.jpg"),
          },
          {
            name: "Shirt 7",
            price: 299,
            gender: "male",
            image: require("./../images/st7.jpg"),
          },
          {
            name: "Shirt 8",
            price: 299,
            gender: "male",
            image: require("./../images/st8.jpg"),
          },
          {
            name: "Shirt 9",
            price: 299,
            gender: "male",
            image: require("./../images/st9.jpg"),
          },
          {
            name: "Shirt 10",
            price: 299,
            gender: "male",
            image: require("./../images/st10.jpg"),
          },
        ],
      },
      {
        category: "Shoes",
        data: [
          {
            name: "Shoes 1",
            price: 6321,
            gender: "male",
            image: require("./../images/s1.jpg"),
          },
          {
            name: "Shoes 2",
            price: 5697,
            gender: "male",
            image: require("./../images/s2.jpg"),
          },
          {
            name: "Shoes 3",
            price: 6547,
            gender: "male",
            image: require("./../images/s3.jpg"),
          },
          {
            name: "Shoes 4",
            price: 9654,
            gender: "male",
            image: require("./../images/s4.jpg"),
          },
          {
            name: "Shoes 5",
            price: 6547,
            gender: "male",
            image: require("./../images/s5.jpg"),
          },
          {
            name: "Shoes 6",
            price: 1236,
            gender: "male",
            image: require("./../images/s6.jpg"),
          },
          {
            name: "Shoes 7",
            price: 987,
            gender: "male",
            image: require("./../images/s7.jpg"),
          },
          {
            name: "Shoes 8",
            price: 879,
            gender: "male",
            image: require("./../images/s8.jpg"),
          },
          {
            name: "Shoes 9",
            price: 6321,
            gender: "male",
            image: require("./../images/s9.jpg"),
          },
          {
            name: "Shoes 10",
            price: 9874,
            gender: "male",
            image: require("./../images/s10.jpg"),
          },
        ],
      },
      {
        category: "Jacket",
        data: [
          {
            name: "Jacket 1",
            price: 399,
            gender: "male",
            image: require("./../images/jt1.jpg"),
          },
          {
            name: "Jacket 2",
            price: 499,
            gender: "male",
            image: require("./../images/jt2.jpg"),
          },
          {
            name: "Jacket 3",
            price: 299,
            gender: "male",
            image: require("./../images/jt3.jpg"),
          },
          {
            name: "Jacket 4",
            price: 299,
            gender: "male",
            image: require("./../images/jt4.jpg"),
          },
          {
            name: "Jacket 5",
            price: 299,
            gender: "male",
            image: require("./../images/jt5.jpg"),
          },
          {
            name: "Jacket 6",
            price: 299,
            gender: "male",
            image: require("./../images/jt6.jpg"),
          },
          {
            name: "Jacket 7",
            price: 299,
            gender: "male",
            image: require("./../images/jt7.jpg"),
          },
          {
            name: "Jacket 8",
            price: 299,
            gender: "male",
            image: require("./../images/jt8.jpg"),
          },
          {
            name: "Jacket 9",
            price: 299,
            gender: "male",
            image: require("./../images/jt9.jpg"),
          },
          {
            name: "Jacket 10",
            price: 299,
            gender: "male",
            image: require("./../images/jt10.jpg"),
          },
        ],
      },
      {
        category: "Trouser",
        data: [
          {
            name: "Trouser 1",
            price: 399,
            gender: "male",
            image: require("./../images/tr1.jpg"),
          },
          {
            name: "Trouser 2",
            price: 499,
            gender: "male",
            image: require("./../images/tr2.jpg"),
          },
          {
            name: "Trouser 3",
            price: 299,
            gender: "male",
            image: require("./../images/tr3.jpg"),
          },
          {
            name: "Trouser 4",
            price: 299,
            gender: "male",
            image: require("./../images/tr4.jpg"),
          },
          {
            name: "Trouser 5",
            price: 299,
            gender: "male",
            image: require("./../images/tr5.jpg"),
          },
          {
            name: "Trouser 6",
            price: 299,
            gender: "male",
            image: require("./../images/tr6.jpg"),
          },
          {
            name: "Trouser 7",
            price: 299,
            gender: "male",
            image: require("./../images/tr7.jpg"),
          },
          {
            name: "Trouser 8",
            price: 299,
            gender: "male",
            image: require("./../images/tr8.jpg"),
          },
          {
            name: "Trouser 9",
            price: 299,
            gender: "male",
            image: require("./../images/tr9.jpg"),
          },
          {
            name: "Trouser 10",
            price: 299,
            gender: "male",
            image: require("./../images/tr10.jpg"),
          },
        ],
      },
      {
        category: "Watch",
        data: [
          {
            name: "Watch 1",
            price: 399,
            gender: "male",
            image: require("./../images/w1.jpg"),
          },
          {
            name: "Watch 2",
            price: 499,
            gender: "male",
            image: require("./../images/w2.jpg"),
          },
          {
            name: "Watch 3",
            price: 299,
            gender: "male",
            image: require("./../images/w3.jpg"),
          },
          {
            name: "Watch 4",
            price: 299,
            gender: "male",
            image: require("./../images/w4.jpg"),
          },
          {
            name: "Watch 5",
            price: 299,
            gender: "male",
            image: require("./../images/w5.jpg"),
          },
          {
            name: "Watch 6",
            price: 299,
            gender: "male",
            image: require("./../images/w6.jpg"),
          },
          {
            name: "Watch 7",
            price: 299,
            gender: "male",
            image: require("./../images/w7.jpg"),
          },
          {
            name: "Watch 8",
            price: 299,
            gender: "male",
            image: require("./../images/w8.jpg"),
          },
          {
            name: "Watch 9",
            price: 299,
            gender: "male",
            image: require("./../images/w9.jpg"),
          },
          {
            name: "Watch 10",
            price: 299,
            gender: "male",
            image: require("./../images/w10.jpg"),
          },
        ],
      },
    ],
  };
  